# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kohKf0FoB4gjK4hv1t8YZqkHz83zLvfv
"""

#시험 점수 자동 채점 프로그램

cut= 65
maximum= 100
minimum= 0

# 시험 점수 입력
num1=int(input('창사코: '))
num2=int(input('선형대수: '))
num3=int(input('컴퓨터 공학: '))

# 시험 점수 출력
print(num1,num2,num3)

# 0~100 사이의 숫자가 아닌 경우
if num1 > maximum or num2 > maximum or num3 > maximum :
  print('잘못된 점수가 입력되었습니다.')

elif num1 < minimum or num2 < minimum or num3 < minimum :
    print('잘못된 점수가 입력되었습니다.')

# 점수가 모두 65점 이상인 경우
elif num1 >= cut and num2 >= cut and num3 >= cut :
    print('합격입니다')

# 한 과목이라도 65점 이하인 경우
else:
  print('불합격입니다. 재수강하세요')