# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kohKf0FoB4gjK4hv1t8YZqkHz83zLvfv
"""

#유저 DB 갱신 프로그램

#dictionary 변수 선언
dicUser = {}

#정보를 입력 받는 함수
def userinfo(comment):
  val = input(comment)
  return val

#이름 입력 받기
name = userinfo('이름: ')
#나이 입력 받기 
age = userinfo('나이: ')
#연락처 입력 받기  
phone = userinfo('연락처: ')

#딕셔너리에 업데이트
dicUser .update({'name': name})
dicUser .update({'age': age})
dicUser .update({'phone': phone})

#딕셔너리 출력
print(dicUser)