# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kohKf0FoB4gjK4hv1t8YZqkHz83zLvfv
"""

#과일 채소 프로그램

#과일 리스트
fruit=['사과','오렌지','포도','파인애플']
#채소 리스트
vegetable=['당근','호박','양상추','브로콜리']

#카테고리 선택
cate = input('등록할 카테고리를 선택해주세요: ')

#채소 카테고리를 선택한 경우
if cate=='채소':
  name = input('등록할 상품명을 입력해주세요: ')
#이미 있는 채소의 경우
  if name in vegetable:
    print('이미 등록된 채소입니다')
#새로운 채소의 경우   
  else:
   vegetable.append(name)  

#과일 카테고리를 선택한 경우
if cate=='과일':
  name = input('등록할 상품명을 입력해주세요: ')
#이미 있는 과일의 경우  
  if name in fruit:
    print('이미 등록된 과일입니다')
#새로운 과일의 경우   
  else:
   fruit.append(name)    

#카테고리 입력을 잘못한 경우
else:
   print('존재하지 않는 카테고리 입니다') 

#카테고리 출력
print(fruit, vegetable)