# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kohKf0FoB4gjK4hv1t8YZqkHz83zLvfv
"""

#과일 채소 프로그램 함수화 (3-1)

#과일 리스트
fruit=['사과','오렌지','포도','파인애플']
#채소 리스트
vegetable=['당근','호박','양상추','브로콜리']

#카테고리별 제품 등록 함수
def addnew(cate, name):
  if cate == "과일":
    name = input('등록할 상품명을 입력해주세요: ')
    if name in fruit:
      print("이미 등록된 과일입니다.")
    else:
            fruit.append(name)
  elif cate == "채소":
    name = input('등록할 상품명을 입력해주세요: ')
    if name in vegetable:
            print("이미 등록된 채소입니다.")
    else:
            vegetable.append(name)
  else:
        print("존재하지 않는 카테고리입니다.")

#카테고리 목록 반환 함수
def getshowlist(fruit,vegetable):
  print(fruit,vegetable)

#함수 사용
cate = input("등록할 카테고리를 선택해주세요: ")
addnew(cate, name)
getshowlist(fruit,vegetable)